### PR TITLE
Converted the homepage into a template

### PR DESCRIPTION
**Pull request by AbhinavMadahar**
I used Laravel Blade's syntax, but I am not sure if I did it correctly. I could not test it because the routing isn't set up.

Also, I removed index.css because Bootstrap will do all our CSS for us anyway

### CODE REVIEW

**Comment by AbhinavMadahar** [comment]
@Charles-T-King/frontend what do you all think? Also, @rvolyar did I do the syntax correctly?

**Comment by rvolyar** [comment]
I think it's beneficial to have the menu in another file (partial) and just inject it into the master template.

**Comment by AbhinavMadahar** [comment]
@rvolyar what should the 2 files be called then?

**Comment by rvolyar** [comment]
menu.blade.php

**Comment by rvolyar** [comment]
put it in a partials folder

**Comment by AbhinavMadahar** [comment]
How about now?

**Comment by rvolyar** [comment]
A couple things.

The master layout should not extend other things. Only other pages like the about page extend it.

Use the @ include method instead of @ yield for the navbar partial in the master layout.  Then in the menu partial you don't need the @ section and @ stop.

[Here's a simple article that should guide you in this task.](https://scotch.io/tutorials/simple-laravel-layouts-using-blade]

**Comment by AbhinavMadahar** [comment]
I have the following filetree set up. Is it good?

-- views
    -- includes
        -- menu.blade.php
        -- footer.blade.php
        -- head.blade.php
    -- layouts
        -- default.blade.php

**Comment by rvolyar** [comment]
Looks good to me.

**Comment by rvolyar** [comment]
You can try merging the pull request.

**Comment by rvolyar** [comment]
Comment out the blade instructions you put in the top of files as they can't be commented out by . Look [here](http://laravel.com/docs/5.0/templates) on how to comment on blade so they don't render on html.

**Pull request merged**
