### PR TITLE
Updated navbar, added named routes

### PR DESCRIPTION
**Pull request by rvolyar**
In this PR, I 

* cleaned up the navbar to show only available pages
* made named routes
* linked navbar links to the named routes
*moved separate page controllers into single pages controller

### CODE REVIEW

**Comment by rvolyar** [comment]
something messed up in my commits so every commit is duplicated

**Comment by rvolyar** [comment]
@AbhinavMadahar any comments before I merge?

**Comment by AbhinavMadahar** [comment]
Looks good

**Comment by AbhinavMadahar** [comment]
Looks good

**Pull request merged**
