### PR TITLE
composer.lock updated

### PR DESCRIPTION
**Pull request by rvolyar**

### CODE REVIEW

**Comment by ChengJeremy** [comment]
What are we doing for servers?

I am in the process of getting Laravel on windows.

**Comment by rvolyar** [comment]
What do you mean by "getting laravel on windows"?  We use git to store code. Cloud9 to edit our code. Hosting will probably be on a digital ocean server.

**Comment by ChengJeremy** [comment]
lol Idk I'm getting it anyway

**Comment by ChengJeremy** [comment]
Abinav mentioned it a lot. Using for PHP?

**Comment by ChengJeremy** [comment]
And as for Cloud9, how do we set it up?

**Comment by ChengJeremy** [comment]
thx

**Comment by rvolyar** [comment]
Yes laravel is a framework we are using for php.

**Comment by rvolyar** [comment]
@ChengJeremy can you try going over the readme file again and see if it will work for you?

**Comment by ChengJeremy** [comment]
[image: Inline image 1]

finally lol
btw you have to delete the "h= " in DB_USERNAME=h=chengjeremy

LOL that was bad

**Comment by rvolyar** [comment]
So everything is working now?

**Comment by ChengJeremy** [comment]
What do we need to do now?

**Comment by ChengJeremy** [comment]
yes everything is working.

**Pull request merged**
